### ISSUE TITLE
Ajout de la validation de la configuration

### ISSUE THREAD

**Issue by restray** [xGoldaxe/webserv#12]
## Collisions

Des serveurs en collision doivent output une log niveau `warning`:
- [x] Avec le meme server_name et port -> "Only the first server will be served"

## Methodes

- [ ] La/les methodes autorisees specifie sur une location doivent etre specifie dans l'enum **`WEBSERV_METHODS`**

**Comment by Vatar** [comment]
Les enums sont très peu définis avant C++11, je ne vois pas comment l'utiliser d'une manière convenable pour avoir un enum {GET, HEAD, POST, DELETE} que je peux utiliser pour comparer un string avec(is_string_in_enum, y'a pas!).
